apiVersion: v1
kind: Service
metadata:
  name: shipping-cost-api
  labels:
    app: shipping-cost-api
spec:
  type: NodePort
  selector:
    app: shipping-cost-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
